### ISSUE TITLE
Client/server requests

### ISSUE THREAD

**Issue by saviord7** [SaviorD7/applicant-service#18]
- [x]  Deploy Flask-server

Names:

- БАЛЛ_ЗА_ДОСТИЖЕНИЯ 
- БАЛЛ_ОЛИМПИАДЫ_И_КОНКУРСЫ 
- ЕСТЬ_АТТЕСТАТ_С_ОТЛИЧИЕМ 
- ЕСТЬ_ДИПЛОМ_С_ОТЛИЧИЕМ 
- ОЦЕНКА_ЗА_СОЧИНЕНИЕ 
- УРОВЕНЬ_ДИПЛОМА 
- ОБЩЕЖИТИЕ_ТИП_ЗАСЕЛЕНИЯ 
- НАПРАВЛЕНИЕ_В_ПРИКАЗЕ_БАЛЛ 
- НАПРАВЛЕНИЕ_В_ПРИКАЗЕ_ОЦЕНКА_1 
- НАПРАВЛЕНИЕ_В_ПРИКАЗЕ_ОЦЕНКА_2 
- НАПРАВЛЕНИЕ_В_ПРИКАЗЕ_ОЦЕНКА_3

_Time spent: 5 hours_

**Comment by RollingHog** [comment]
Не хватает полей 
* НАПРАВЛЕНИЕ_В_ПРИКАЗЕ_ПРЕДМЕТ_1_ПРИОРИТЕТ
* НАПРАВЛЕНИЕ_В_ПРИКАЗЕ_ПРЕДМЕТ_2_ПРИОРИТЕТ
* НАПРАВЛЕНИЕ_В_ПРИКАЗЕ_ПРЕДМЕТ_3_ПРИОРИТЕТ

Непонятно как использовать 
* НАПРАВЛЕНИЕ_В_ПРИКАЗЕ_БАЛЛ_ЕГЭ_С_ОЛИМПИАДОЙ
* НАПРАВЛЕНИЕ_В_ПРИКАЗЕ_ОЛИМПИАДА_ЗА_100_БАЛЛОВ

Остальное сделано 
35c8bbf
пуллреквест лень делать, сорян
